[package]
name = "secure-transport-proxy"
version = "0.0.1"
authors = ["Andrew Dunham <adunham@stripe.com>"]

[dependencies]
ansi_term = "0.7"
clap = "1.5.5"
fern = "0.3.5"
log = "0.3"
security-framework = "0.1.3"
time = "0.1"
